name: deployDist
on:
  - push:
      branches:
        - main
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        run: |
          echo "cloning the repo ....."
          echo "${{toJson(github)}}"
          git clone "https://github.com/${{github.repository}}.git"
          echo "Cloned Completely."

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run greeting script
        run: |
          echo "Hello, World!"
          echo "This is a greeting from GitHub Actions."  